version: '3.9'

services:
  mariadb:
    image: mariadb:11.1
    env_file:
      - ./db/root.env
      - ./db/db.env
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/conf/my-resolve.cnf:/etc/mysql/conf.d/my-resolve.cnf
    networks:
      - db_net

  php:
    build:
      context: ./php
    volumes:
      - ./www:/var/www/html/www
    env_file:
      - ./db/db.env
    networks:
      - db_net
      - dmz

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html/www
      - ./certificates/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./certificates/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./letsencrypt:/etc/letsencrypt
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt/archive:/etc/letsencrypt/archive
    depends_on:
      - php
    networks:
      - dmz

volumes:
  dbdata:
  letsencrypt:

networks:
  dmz:
  db_net: